// The Event interface represents an event which takes place on an EventTarget.

// An event can be triggered by the user action e.g., clicking the mouse button or 
// tapping the keyboard, or generated by APIs to represent the progress of an asynchronous 
// task. It can also be triggered programmatically, such as by calling the HTMLElement.click() 
// method of an element, or by defining the event, then sending it to a specified target using 
// EventTarget.dispatchEvent().

console.log("Getting started with event");

